### ISSUE TITLE
Arranging insert files

### ISSUE THREAD

**Issue by Onitsiky** [Onitsiky/Donnee2#28]
Pour les insert, il faut en premier insérer les données des tables qui ne requièrent pas de clés étrangères, et celles-ci après 
Alors, renommer chaque fichier selon leur ordre d'insertion.
Exemple : insert_chauffeur.sql => 11_insert_chauffeur.sql

**Comment by Fitia-Randriantseheno** [comment]
Done

**Comment by Onitsiky** [comment]
Not yet
